### ISSUE TITLE
Deformable DETR code

### ISSUE THREAD

**Issue by yuzitian** [Fangyi-Chen/SQR#2]
Hi, thank you for a good job. You did experiments with DETR-like models in your paper. I would like to ask if it is convenient for you to open the source code of the experiment with Deformable DETR?

**Comment by Fangyi-Chen** [comment]
Hi,

Yes we plan to release sqr-deformable detr in a couple of weeks as the team is on leave

**Comment by Fangyi-Chen** [comment]
[update] Released. Please refer to the readme.md 

Recommend following the original deformable detr setting (32 as batchsize 8*A100 x 4 imgs per GPU ).  Expecting 45.8±0.2 AP.  Thanks

**Comment by yuzitian** [comment]
Thank you very much for your reply. I ran your code as soon as you replied. Due to insufficient memory on my device, I am unable to use the same configuration as you. But I got a bad result. After carefully reviewing the code, I found that you did not update the reference points during the decoder process. May I ask why you are handling this in this place?

**Comment by Fangyi-Chen** [comment]
Hi,

I am not sure what hyperparameter you changed in config, but some of them are critical, such as query number, feature dimension, encoder layer number, decoder layer number, etc.

For sqr-deformable-detr, we do not collect the reference points, because if the reg_branch is None (one stage), the reference points are not updated, so for SQR, it is also unnecessary to do that. 

If you do not have enough memory to run your research, I recommend using sqr-adamixer which runs well with 8x24GB card.

**Comment by yuzitian** [comment]
Thank you a lot for your advice. Wish you have a nice day !!
